In [1]:
import pandas as pd
from src.config import SRC

### This is just a quick and dirty notebook that helps me to perform some data management tasks that need to be done once.

In [3]:
frame = pd.read_pickle(SRC / "data_management" / "processed_data" / "proc_2022-02-19_val2_euro600.pkl")
frame

,ticker,date,industry,de_ticker,enterpriseValue,marketCap,forwardPE,trailingPE,profitMargins,floatShares,...,MC_percentile,PS_percentile,EToRev_precentile,EToEbitda_percentile,FFA_m_percentile,FF_Cons_actual_percentile,ROE(inv)_percentile,FFQ(inv)_g_percentile,FFQ(inv)_a_percentile,FFQ(inv)_m_percentile
III.L,III.L,2022-02-19,NaN,NaN,NaN,1.277826e+10,0.110961,4.544825,NaN,NaN,...,0.446809,NaN,NaN,NaN,0.624113,0.659574,NaN,0.171986,0.680851,0.833333
MAERSK-B.CO,MAERSK-B.CO,2022-02-19,Logistik/Transport,DP4B,4.661031e+11,4.100938e+11,9.996862,5.108443,0.24107,1.096328e+07,...,0.975177,0.817376,0.762411,0.696809,0.047872,0.030142,0.127660,NaN,NaN,NaN
A2A.MI,A2A.MI,2022-02-19,Versorger,EAM,9.617364e+09,4.777304e+09,14.254545,8.858757,0.06496,1.492116e+09,...,0.163121,0.120567,0.224291,0.223404,0.530142,0.386525,0.464539,NaN,NaN,NaN
AAK.ST,AAK.ST,2022-02-19,Nahrungsmittel/Agrar,6AA0,5.086606e+10,4.671113e+10,24.093332,33.271954,0.04053,1.792679e+08,...,0.755319,0.320922,0.283688,0.508865,0.774823,0.872340,0.501773,0.601064,0.583333,0.595745
AALB.AS,AALB.AS,2022-02-19,Industrie/Mischkonzerne,AACA,6.644118e+09,5.778911e+09,21.866108,29.049470,0.07039,1.055469e+08,...,0.219858,0.448582,0.425532,0.450355,0.349291,0.581560,0.590426,0.758865,0.328014,0.304965
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
WRT1V.HE,WRT1V.HE,2022-02-19,Maschinenbau,MTA,8.015905e+09,6.000534e+09,17.842106,35.936398,0.03777,3.875746e+08,...,0.235816,0.328014,0.359929,0.624113,0.301418,0.542553,0.751773,0.769504,0.432624,0.358156
YAR.OL,YAR.OL,2022-02-19,Chemie,IU2,1.249332e+11,1.141937e+11,10.955523,19.992863,0.04535,1.574867e+08,...,0.902482,0.828014,0.764184,0.838652,0.214539,0.455674,0.709220,0.264184,0.485816,0.640071
ZAL.DE,ZAL.DE,2022-02-19,Handel/E-Commerce,ZAL,1.926640e+10,1.493454e+10,55.588783,56.755726,0.02828,1.905848e+08,...,0.498227,0.358156,0.372340,0.778369,0.875887,0.595745,0.507092,0.228723,0.671986,0.861702
ROSE.SW,ROSE.SW,2022-02-19,Pharma,ZRE,2.505624e+09,1.687552e+09,-40.691357,NaN,-0.09905,9.320634e+06,...,0.008865,0.242908,0.304078,0.031915,0.925532,0.945035,0.982270,0.670213,0.661348,0.698582
ZURN.SW,ZURN.SW,2022-02-19,Finanzdienstleistungen,ZFIN,6.071996e+10,6.441756e+10,12.910714,14.740061,0.06792,1.485140e+08,...,0.820922,0.210993,0.145390,0.214539,0.198582,0.049645,0.482270,0.620567,0.771277,0.769504

In [4]:
frame = pd.read_csv("val_val_de.csv")
frame

,Unnamed: 0,name,wkn,index,de_ticker,ticker,industry,ISIN
0,0,1&1 AG,554550,DE,1U1,1U1.F,Telekom,DE0005545503
1,1,11 88 0 Solutions AG,511880,DE,TGT,TGT.F,Telekom,DE0005118806
2,2,2G energy AG,A0HL8N,DE,2GB,2GB.F,Sonstige Technologie,DE000A0HL8N9
3,3,3U Holding AG,516790,DE,UUU,UUU.F,Telekom,DE0005167902
4,4,7C Solarparken AG,A11QW6,DE,HRPK,HRPK.F,Erneuerbare Energien,DE000A11QW68
...,...,...,...,...,...,...,...,...
396,396,Wüstenrot & Württembergische AG,805100,DE,WUW,WUW.F,Finanzdienstleistungen,DE0008051004
397,397,YMOS AG O.N.,784730,DE,YMO,YMO.F,Fahrzeuge,DE0007847303
398,398,YOC AG,593273,DE,YOC,YOC.F,Dienstleistungen,DE0005932735
399,399,ZHONGDE WASTE TECHNOLOGY,ZDWT01,DE,ZEF,ZEF.F,Dienstleistungen,DE000ZDWT018
400,400,Zooplus AG,511170,DE,ZO1,ZO1.F,Handel/E-Commerce,DE0005111702

In [5]:
#frame = pd.read_csv("val_val_NYSEStocks.csv")


try:
    frame.drop('Unnamed: 0', axis=1, inplace=True)
except:
    pass
try:
    frame.drop('Unnamed: 0.1', axis = 1, inplace = True)
except:
    pass
try:
    frame.drop('Unnamed: 0.2', axis = 1, inplace=True)
except:
    pass

In [6]:
frame

,name,wkn,index,de_ticker,ticker,industry,ISIN
0,1&1 AG,554550,DE,1U1,1U1.F,Telekom,DE0005545503
1,11 88 0 Solutions AG,511880,DE,TGT,TGT.F,Telekom,DE0005118806
2,2G energy AG,A0HL8N,DE,2GB,2GB.F,Sonstige Technologie,DE000A0HL8N9
3,3U Holding AG,516790,DE,UUU,UUU.F,Telekom,DE0005167902
4,7C Solarparken AG,A11QW6,DE,HRPK,HRPK.F,Erneuerbare Energien,DE000A11QW68
...,...,...,...,...,...,...,...
396,Wüstenrot & Württembergische AG,805100,DE,WUW,WUW.F,Finanzdienstleistungen,DE0008051004
397,YMOS AG O.N.,784730,DE,YMO,YMO.F,Fahrzeuge,DE0007847303
398,YOC AG,593273,DE,YOC,YOC.F,Dienstleistungen,DE0005932735
399,ZHONGDE WASTE TECHNOLOGY,ZDWT01,DE,ZEF,ZEF.F,Dienstleistungen,DE000ZDWT018
400,Zooplus AG,511170,DE,ZO1,ZO1.F,Handel/E-Commerce,DE0005111702

In [ ]:
frame.replace("Ticker-Symbol:", "not_found", inplace=True)
frame

In [7]:
frame.to_csv("val2_de.csv")    
frame.to_pickle("val2_de.pkl")